### ISSUE TITLE
Confusion around book icons 

### ISSUE THREAD

**Issue by qmanderson1** [GSA/digitalgov-pra#157]
It wasn't clear to users that the book icon meant they were looking at a glossary term and could click for a definition. 

<img width="562" alt="Screen Shot 2019-05-07 at 3 03 31 PM" src="https://user-images.githubusercontent.com/23083747/57326075-9e720f00-70d9-11e9-922a-04f96717b51c.png">

**Comment by cmajel** [comment]
per convo with @qmanderson1, it sounds like we asked users if they knew what this meant, rather than have them try to find the definition of a specific term. It seem we need additional testing to determine if:

* if these items register as clickable
* users can discover that they can click on these items to find a definition

**Comment by cmajel** [comment]
closing as it's been replaced by #167
