### ISSUE TITLE
Re-format Process Diagram

### ISSUE THREAD

**Issue by qmanderson1** [GSA/digitalgov-pra#18]
User comments: 

- Would want a horizontal timeline with an overall estimate of how long the overall process would take
- not intuitive - wanted a count back clock

**Comment by cmajel** [comment]
This has been updated based on user feedback and as currently live:

https://federalist-proxy.app.cloud.gov/demo/gsa/digitalgov-pra/clearance-process/

A few notes:
* We did not add a count back clock because the agency part of this process, which is where most of the time lies, is not standard in terms of steps or time across agencies.
* We did add language to the diagram intro on overall timelines: `Most agencies estimate 6 to 9 months for PRA clearance from start to finish. By law, this process includes at least 3 months of public comment.` 
* We kept this as a vertical layout because of the number of steps and to make it easier to scan down like a table of contents. The vertical layout also has the benefit of working better responsively across device sizes.  

Closing this out since adjustments have been considered.
